### PR TITLE
fix: genericmeta not available 3.7+

### PR DESCRIPTION
**Pull request by aarnphm**
Signed-off-by: Aaron Pham <29749331+aarnphm@users.noreply.github.com>

### CODE REVIEW

**Comment by bojiang** [comment]
@aarnphm mypy broken

**Comment by bojiang** [comment]
shall i drop the Python3.6 support?

**Comment by parano** [comment]
> shall i drop the Python3.6 support?

Bentoml has dropped 3.6 😉

**Comment by yetone** [comment]
typing_extension is not a python standard library, so why does it depend on the python version? I've always been able to do it in version 3.8

**Comment by aarnphm** [comment]
> `typing_extensions` is not a python standard library, so why does it depend on the python version? I've always been able to do it in version 3.8

This due to when we don't lock `typing_extension`, it will try to install the latest version, which is `4.0.0`. Unless we pin `typing_extension` the errors will always occur with both `mypy` and `pyright`

**Comment by bojiang** [comment]
https://github.com/python/typing/tree/master/typing_extensions#overview

**Comment by bojiang** [comment]
This is still right. included in #19

**Pull request closed without merging**
